#!/bin/bash
echo "🚀 BLYTZ DEMO DATA IMPORT GUIDE"
echo "================================"
echo ""
echo "🔧 STEP 1: Access Firebase Console"
echo "   Go to: https://console.firebase.google.com/project/blytz-e9935/firestore"
echo ""
echo "📁 STEP 2: Create Collections and Documents"
echo ""
echo "Collection: users"
echo "  Document ID: seller_vintage_001"
echo "  Data: Copy from firebase_import.json → users → seller_vintage_001"
echo ""
echo "  Document ID: seller_tech_001" 
echo "  Data: Copy from firebase_import.json → users → seller_tech_001"
echo ""
echo "Collection: sellers"
echo "  Document ID: seller_vintage_001"
echo "  Data: Copy from firebase_import.json → sellers → seller_vintage_001"
echo ""
echo "Collection: products"
echo "  Document ID: prod_vintage_001"
echo "  Data: Copy from firebase_import.json → products → prod_vintage_001"
echo ""
echo "Collection: liveStreams"
echo "  Document ID: stream_001"
echo "  Data: Copy from firebase_import.json → liveStreams → stream_001"
echo ""
echo "Collection: featuredStreams"
echo "  Document ID: featured_001"
echo "  Data: Copy from firebase_import.json → featuredStreams → featured_001"
echo ""
echo "✅ After import, restart your app: npm start"
