#!/bin/bash
echo "🔥 Populating Firestore with complete demo data..."

# Create users
echo "👥 Creating users..."
curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/users/seller_vintage_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"uid":{"stringValue":"seller_vintage_001"},"email":{"stringValue":"vintage@demo.com"},"displayName":{"stringValue":"Vintage Vibes"},"photoURL":{"stringValue":"https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop&crop=face"},"phoneNumber":{"stringValue":"+1234567890"},"emailVerified":{"booleanValue":true},"role":{"stringValue":"seller"},"isVerified":{"booleanValue":true},"rating":{"doubleValue":4.8},"totalSales":{"integerValue":2847},"followers":{"integerValue":15234},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/users/seller_tech_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"uid":{"stringValue":"seller_tech_001"},"email":{"stringValue":"tech@demo.com"},"displayName":{"stringValue":"Tech Deals Hub"},"photoURL":{"stringValue":"https://images.unsplash.com/photo-1494790108755-2616b612b5b9?w=150&h=150&fit=crop&crop=face"},"phoneNumber":{"stringValue":"+1234567891"},"emailVerified":{"booleanValue":true},"role":{"stringValue":"seller"},"isVerified":{"booleanValue":true},"rating":{"doubleValue":4.9},"totalSales":{"integerValue":5639},"followers":{"integerValue":28471},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/users/seller_artisan_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"uid":{"stringValue":"seller_artisan_001"},"email":{"stringValue":"artisan@demo.com"},"displayName":{"stringValue":"Artisan Crafts"},"photoURL":{"stringValue":"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face"},"phoneNumber":{"stringValue":"+1234567892"},"emailVerified":{"booleanValue":true},"role":{"stringValue":"seller"},"isVerified":{"booleanValue":true},"rating":{"doubleValue":4.7},"totalSales":{"integerValue":1234},"followers":{"integerValue":8923},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

# Create sellers
echo "🏪 Creating sellers..."
curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/sellers/seller_vintage_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"seller_vintage_001"},"userId":{"stringValue":"seller_vintage_001"},"businessName":{"stringValue":"Vintage Vibes Emporium"},"businessDescription":{"stringValue":"Curating authentic vintage pieces from the 60s, 70s, and 80s. Specializing in clothing, accessories, and home decor."},"businessLogo":{"stringValue":"https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=200&h=200&fit=crop"},"businessCategory":{"stringValue":"Vintage & Collectibles"},"verificationStatus":{"stringValue":"verified"},"totalSales":{"integerValue":2847},"rating":{"doubleValue":4.8},"followers":{"integerValue":15234},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/sellers/seller_tech_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"seller_tech_001"},"userId":{"stringValue":"seller_tech_001"},"businessName":{"stringValue":"Tech Deals Hub"},"businessDescription":{"stringValue":"Latest tech gadgets, gaming gear, and electronics at unbeatable prices. All items tested and verified."},"businessLogo":{"stringValue":"https://images.unsplash.com/photo-1498049794561-7780e7231661?w=200&h=200&fit=crop"},"businessCategory":{"stringValue":"Electronics & Gaming"},"verificationStatus":{"stringValue":"verified"},"totalSales":{"integerValue":5639},"rating":{"doubleValue":4.9},"followers":{"integerValue":28471},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/sellers/seller_artisan_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"seller_artisan_001"},"userId":{"stringValue":"seller_artisan_001"},"businessName":{"stringValue":"Artisan Craft Studio"},"businessDescription":{"stringValue":"Handcrafted jewelry and accessories made with love. Each piece is unique and tells a story."},"businessLogo":{"stringValue":"https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=200&h=200&fit=crop"},"businessCategory":{"stringValue":"Handmade & Artisan"},"verificationStatus":{"stringValue":"verified"},"totalSales":{"integerValue":1234},"rating":{"doubleValue":4.7},"followers":{"integerValue":8923},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

# Create products
echo "📦 Creating products..."
curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/products/prod_vintage_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"prod_vintage_001"},"name":{"stringValue":"Vintage 70s Leather Jacket"},"description":{"stringValue":"Authentic 1970s brown leather motorcycle jacket. Excellent condition with original patches and studs."},"price":{"doubleValue":85},"startingPrice":{"doubleValue":45},"currentPrice":{"doubleValue":67.5},"reservePrice":{"doubleValue":80},"sellerId":{"stringValue":"seller_vintage_001"},"category":{"stringValue":"Vintage Clothing"},"images":{"arrayValue":{"values":[{"stringValue":"https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=400&h=400&fit=crop"},{"stringValue":"https://images.unsplash.com/photo-1593032465175-481ac7f401f0?w=400&h=400&fit=crop"}]}},"condition":{"stringValue":"excellent"},"brand":{"stringValue":"Harley Davidson"},"size":{"stringValue":"L"},"color":{"stringValue":"Brown"},"material":{"stringValue":"Genuine Leather"},"tags":{"arrayValue":{"values":[{"stringValue":"vintage"},{"stringValue":"leather"},{"stringValue":"motorcycle"},{"stringValue":"70s"},{"stringValue":"biker"}]}},"isActive":{"booleanValue":true},"auctionEndTime":{"timestampValue":"2024-01-01T02:00:00.000Z"},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/products/prod_vintage_002" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"prod_vintage_002"},"name":{"stringValue":"Vintage Gucci Bamboo Handbag"},"description":{"stringValue":"Classic Gucci bamboo handle handbag from the 1980s. Authentic with serial number and dust bag."},"price":{"doubleValue":120},"startingPrice":{"doubleValue":75},"currentPrice":{"doubleValue":95},"reservePrice":{"doubleValue":110},"sellerId":{"stringValue":"seller_vintage_001"},"category":{"stringValue":"Vintage Accessories"},"images":{"arrayValue":{"values":[{"stringValue":"https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=400&fit=crop"},{"stringValue":"https://images.unsplash.com/photo-1590739241834-04c8a4597819?w=400&h=400&fit=crop"}]}},"condition":{"stringValue":"very_good"},"brand":{"stringValue":"Gucci"},"color":{"stringValue":"Brown"},"material":{"stringValue":"Leather"},"tags":{"arrayValue":{"values":[{"stringValue":"vintage"},{"stringValue":"gucci"},{"stringValue":"handbag"},{"stringValue":"luxury"},{"stringValue":"bamboo"}]}},"isActive":{"booleanValue":true},"auctionEndTime":{"timestampValue":"2024-01-01T03:00:00.000Z"},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/products/prod_vintage_003" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"prod_vintage_003"},"name":{"stringValue":"Vintage 60s Silk Scarf"},"description":{"stringValue":"Beautiful silk scarf with psychedelic patterns from the 1960s. Rare collectible piece."},"price":{"doubleValue":35},"startingPrice":{"doubleValue":15},"currentPrice":{"doubleValue":28},"reservePrice":{"doubleValue":30},"sellerId":{"stringValue":"seller_vintage_001"},"category":{"stringValue":"Vintage Accessories"},"images":{"arrayValue":{"values":[{"stringValue":"https://images.unsplash.com/photo-1601370552761-d129028bd833?w=400&h=400&fit=crop"}]}},"condition":{"stringValue":"good"},"brand":{"stringValue":"Hermès"},"color":{"stringValue":"Multi-color"},"material":{"stringValue":"Silk"},"tags":{"arrayValue":{"values":[{"stringValue":"vintage"},{"stringValue":"scarf"},{"stringValue":"silk"},{"stringValue":"60s"},{"stringValue":"psychedelic"}]}},"isActive":{"booleanValue":true},"auctionEndTime":{"timestampValue":"2024-01-01T01:30:00.000Z"},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/products/prod_tech_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"prod_tech_001"},"name":{"stringValue":"Razer Gaming Headset RGB"},"description":{"stringValue":"Professional gaming headset with 7.1 surround sound, RGB lighting, and noise-canceling mic."},"price":{"doubleValue":89.99},"startingPrice":{"doubleValue":45},"currentPrice":{"doubleValue":67.5},"reservePrice":{"doubleValue":75},"sellerId":{"stringValue":"seller_tech_001"},"category":{"stringValue":"Electronics"},"images":{"arrayValue":{"values":[{"stringValue":"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop"},{"stringValue":"https://images.unsplash.com/photo/1599669454699-248893623440?w=400&h=400&fit=crop"}]}},"condition":{"stringValue":"new"},"brand":{"stringValue":"Razer"},"color":{"stringValue":"Black"},"tags":{"arrayValue":{"values":[{"stringValue":"gaming"},{"stringValue":"headset"},{"stringValue":"rgb"},{"stringValue":"surround"},{"stringValue":"razer"}]}},"isActive":{"booleanValue":true},"auctionEndTime":{"timestampValue":"2024-01-01T01:30:00.000Z"},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/products/prod_tech_002" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"prod_tech_002"},"name":{"stringValue":"Corsair RGB Mechanical Keyboard"},"description":{"stringValue":"RGB mechanical gaming keyboard with blue switches and programmable keys. Perfect for gaming and typing."},"price":{"doubleValue":129.99},"startingPrice":{"doubleValue":65},"currentPrice":{"doubleValue":95},"reservePrice":{"doubleValue":110},"sellerId":{"stringValue":"seller_tech_001"},"category":{"stringValue":"Electronics"},"images":{"arrayValue":{"values":[{"stringValue":"https://images.unsplash.com/photo-1595225476474-87563907a212?w=400&h=400&fit=crop"},{"stringValue":"https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&h=400&fit=crop"}]}},"condition":{"stringValue":"new"},"brand":{"stringValue":"Corsair"},"color":{"stringValue":"Black"},"tags":{"arrayValue":{"values":[{"stringValue":"gaming"},{"stringValue":"keyboard"},{"stringValue":"mechanical"},{"stringValue":"rgb"},{"stringValue":"corsair"}]}},"isActive":{"booleanValue":true},"auctionEndTime":{"timestampValue":"2024-01-01T02:30:00.000Z"},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/products/prod_tech_003" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"prod_tech_003"},"name":{"stringValue":"Logitech Wireless Gaming Mouse"},"description":{"stringValue":"High-precision wireless gaming mouse with 20,000 DPI sensor and customizable RGB lighting."},"price":{"doubleValue":79.99},"startingPrice":{"doubleValue":40},"currentPrice":{"doubleValue":62.5},"reservePrice":{"doubleValue":70},"sellerId":{"stringValue":"seller_tech_001"},"category":{"stringValue":"Electronics"},"images":{"arrayValue":{"values":[{"stringValue":"https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop"}]}},"condition":{"stringValue":"new"},"brand":{"stringValue":"Logitech"},"color":{"stringValue":"Black"},"tags":{"arrayValue":{"values":[{"stringValue":"gaming"},{"stringValue":"mouse"},{"stringValue":"wireless"},{"stringValue":"precision"},{"stringValue":"logitech"}]}},"isActive":{"booleanValue":true},"auctionEndTime":{"timestampValue":"2024-01-01T02:00:00.000Z"},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/products/prod_jewelry_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"prod_jewelry_001"},"name":{"stringValue":"Handmade Silver Moon Necklace"},"description":{"stringValue":"Beautiful handcrafted sterling silver necklace with moon pendant. Perfect for everyday wear or special occasions."},"price":{"doubleValue":45},"startingPrice":{"doubleValue":25},"currentPrice":{"doubleValue":32},"reservePrice":{"doubleValue":40},"sellerId":{"stringValue":"seller_artisan_001"},"category":{"stringValue":"Handmade Jewelry"},"images":{"arrayValue":{"values":[{"stringValue":"https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop"}]}},"condition":{"stringValue":"new"},"brand":{"stringValue":"Artisan Crafts"},"color":{"stringValue":"Silver"},"material":{"stringValue":"Sterling Silver"},"tags":{"arrayValue":{"values":[{"stringValue":"handmade"},{"stringValue":"jewelry"},{"stringValue":"necklace"},{"stringValue":"silver"},{"stringValue":"moon"}]}},"isActive":{"booleanValue":true},"auctionEndTime":{"timestampValue":"2024-01-01T01:30:00.000Z"},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/products/prod_jewelry_002" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"prod_jewelry_002"},"name":{"stringValue":"Artisan Rose Gold Ring"},"description":{"stringValue":"Elegant rose gold plated ring with intricate Celtic design. Adjustable size for perfect fit."},"price":{"doubleValue":35},"startingPrice":{"doubleValue":20},"currentPrice":{"doubleValue":28},"reservePrice":{"doubleValue":32},"sellerId":{"stringValue":"seller_artisan_001"},"category":{"stringValue":"Handmade Jewelry"},"images":{"arrayValue":{"values":[{"stringValue":"https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop"}]}},"condition":{"stringValue":"new"},"brand":{"stringValue":"Artisan Crafts"},"color":{"stringValue":"Rose Gold"},"material":{"stringValue":"Rose Gold Plated"},"tags":{"arrayValue":{"values":[{"stringValue":"handmade"},{"stringValue":"jewelry"},{"stringValue":"ring"},{"stringValue":"rose gold"},{"stringValue":"celtic"}]}},"isActive":{"booleanValue":true},"auctionEndTime":{"timestampValue":"2024-01-01T02:00:00.000Z"},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

# Create live streams
echo "📺 Creating live streams..."
curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/liveStreams/stream_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"stream_001"},"title":{"stringValue":"🔥 Vintage Designer Collection LIVE"},"sellerId":{"stringValue":"seller_vintage_001"},"sellerName":{"stringValue":"Vintage Vibes"},"sellerAvatar":{"stringValue":"https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop&crop=face"},"startTime":{"timestampValue":"2024-01-01T00:00:00.000Z"},"status":{"stringValue":"live"},"productIds":{"arrayValue":{"values":[{"stringValue":"prod_vintage_001"},{"stringValue":"prod_vintage_002"},{"stringValue":"prod_vintage_003"}]}},"thumbnailUrl":{"stringValue":"https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=400&h=300&fit=crop"},"viewers":{"integerValue":1847},"category":{"stringValue":"Vintage Fashion"},"currentBid":{"doubleValue":67.5},"productCount":{"integerValue":3},"playbackUrl":{"stringValue":"https://fcc3ddae59ed.us-west-2.playback.live-video.net/api/video/v1/us-west-2.893648527354.channel.DmumNckWFTqz.m3u8"},"isFeatured":{"booleanValue":true},"duration":{"integerValue":0},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/liveStreams/stream_002" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"stream_002"},"title":{"stringValue":"🎮 Gaming Gear Auction LIVE"},"sellerId":{"stringValue":"seller_tech_001"},"sellerName":{"stringValue":"Tech Deals Hub"},"sellerAvatar":{"stringValue":"https://images.unsplash.com/photo-1494790108755-2616b612b5b9?w=150&h=150&fit=crop&crop=face"},"startTime":{"timestampValue":"2024-01-01T00:00:00.000Z"},"status":{"stringValue":"live"},"productIds":{"arrayValue":{"values":[{"stringValue":"prod_tech_001"},{"stringValue":"prod_tech_002"},{"stringValue":"prod_tech_003"}]}},"thumbnailUrl":{"stringValue":"https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop"},"viewers":{"integerValue":3264},"category":{"stringValue":"Electronics"},"currentBid":{"doubleValue":95},"productCount":{"integerValue":3},"playbackUrl":{"stringValue":"https://fcc3ddae59ed.us-west-2.playback.live-video.net/api/video/v1/us-west-2.893648527354.channel.xhP3ExfcX8ON.m3u8"},"isFeatured":{"booleanValue":true},"duration":{"integerValue":0},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/liveStreams/stream_003" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"stream_003"},"title":{"stringValue":"💎 Handmade Jewelry Showcase"},"sellerId":{"stringValue":"seller_artisan_001"},"sellerName":{"stringValue":"Artisan Crafts"},"sellerAvatar":{"stringValue":"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face"},"startTime":{"timestampValue":"2024-01-01T00:00:00.000Z"},"status":{"stringValue":"live"},"productIds":{"arrayValue":{"values":[{"stringValue":"prod_jewelry_001"},{"stringValue":"prod_jewelry_002"}]}},"thumbnailUrl":{"stringValue":"https://images.unsplash.com/photo/1515562141207-7a88fb7ce338?w=400&h=300&fit=crop"},"viewers":{"integerValue":892},"category":{"stringValue":"Handmade"},"currentBid":{"doubleValue":28},"productCount":{"integerValue":2},"playbackUrl":{"stringValue":"https://fcc3ddae59ed.us-west-2.playback.live-video.net/api/video/v1/us-west-2.893648527354.channel.Y7d7TkuqZ9dR.m3u8"},"isFeatured":{"booleanValue":false},"duration":{"integerValue":0},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"},"updatedAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

# Create featured streams
echo "⭐ Creating featured streams..."
curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/featuredStreams/featured_001" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"featured_001"},"streamId":{"stringValue":"stream_001"},"title":{"stringValue":"🔥 Vintage Designer Collection"},"sellerName":{"stringValue":"Vintage Vibes"},"viewers":{"integerValue":2847},"thumbnailUrl":{"stringValue":"https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=400&h=300&fit=crop"},"category":{"stringValue":"Fashion"},"priority":{"integerValue":1},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/featuredStreams/featured_002" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"featured_002"},"streamId":{"stringValue":"stream_002"},"title":{"stringValue":"🎮 Gaming Gear Live"},"sellerName":{"stringValue":"Tech Deals Hub"},"viewers":{"integerValue":5639},"thumbnailUrl":{"stringValue":"https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop"},"category":{"stringValue":"Electronics"},"priority":{"integerValue":2},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

curl -X PATCH "https://firestore.googleapis.com/v1/projects/blytz-e9935/databases/(default)/documents/featuredStreams/featured_003" \
  -H "Content-Type: application/json" \
  -d '{"fields":{"id":{"stringValue":"featured_003"},"streamId":{"stringValue":"stream_003"},"title":{"stringValue":"💎 Handmade Treasures"},"sellerName":{"stringValue":"Artisan Crafts"},"viewers":{"integerValue":892},"thumbnailUrl":{"stringValue":"https://images.unsplash.com/photo/1515562141207-7a88fb7ce338?w=400&h=300&fit=crop"},"category":{"stringValue":"Handmade"},"priority":{"integerValue":3},"createdAt":{"timestampValue":"2024-01-01T00:00:00.000Z"}}}'

echo "✅ Complete demo data populated successfully!"
echo "🚀 Restart your app - HomeScreen should now load all data!"